### PR TITLE
Merge darwin/libdispatch-806 to master and apply Linux build fixes

### PR DESCRIPTION
**Pull request by das**
Merge tag darwin/libdispatch-806 on darwin/trunk.

This includes Apple source drops libdispatch-743, libdispatch-749 & libdispatch-806 as well as all the github PR’s that we’ve pulled back into our internal repository since PR #142 (along with any changes made to these during internal review and testing on Darwin.)

One of the bigger changes included is a switch away from libkqueue to a native epoll()-based event loop backend

@dgrove-oss has a patch ready to apply on top of this with Linux build fixes

### CODE REVIEW

**Comment by das** [comment]
w.r.t Swift 3.1 backport for this, the number of diffs between master and swift-3.1-branch is so small right now (and all look like they should be included in Swift 3.1) that it probably makes sense to just merge master into swift-3.1-branch after we merge this ?

**Comment by das** [comment]
@swift-ci Please test

**Comment by das** [comment]
looks like the CI build failed with
```
make[1]: Entering directory '/home/buildnode/disk2/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-libdispatch/libpwq'
make[1]: *** No rule to make target 'distclean'.  Stop.
make[1]: Leaving directory '/home/buildnode/disk2/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-libdispatch/libpwq'
Makefile:457: recipe for target 'distclean-recursive' failed
make: *** [distclean-recursive] Error 1
```

@dgrove-oss is that something new with this branch ?

**Comment by das** [comment]
this seems suspicious

```
autoreconf: configure.ac: adding subdirectory libpwq to autoreconf
autoreconf: Entering directory `libpwq'
autoreconf: configure.ac: not using Autoconf
autoreconf: Leaving directory `libpwq'
```

and there was no configure of `libpwq`

maybe this is a submodule initialization/checkout issue again ?

**Comment by dgrove-oss** [comment]
I agree it looks like the PR didn't do the submodule init/update step when it checkout out libdispatch.  When that happens, the build  "succeeds" by configuring libdispatch to not use libpwq and we manage to build a libdispatch.so but this is a fairly broken configuration.  It falls over on the 'make distclean'  because the top-level Makefile includes libpwq as a subdir, but libpwq is empty (and therefore not configured or included in the build).

Post merge, we probably should try to fail the build earlier instead of allowing Linux to build without libpwq (at least for as long as we have libpwq as a submodule).  I think a tweak to the configure.ac would do it.

**Comment by das** [comment]
ok, thanks, makes sense, I'll go ahead and merge without despite the CI build failure then, given you had built this manually for Linux with the #216 patch.

**Pull request merged**
