### PR TITLE
build: support system installed BlocksRuntime

### PR DESCRIPTION
**Pull request by compnerd**
This uses the standard CMake mechanism for finding the blocks runtime.
If one is not found, one will be provided for you.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @MadCoder @millenomi

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by MadCoder** [comment]
What is the motivation here? I'm worried about random blocks runtimes, we've made fixes to the copy we have.

**Comment by compnerd** [comment]
The swift instructions tell you to install and build against the blocks runtime (via apt-get).  This enables that.  It also allows you to switch between the version in s-f-l or dispatch or if you have a copy checked out (like libclosure) or from compiler-rt.

**Comment by MadCoder** [comment]
mmk

**Pull request merged**
