### PR TITLE
consider affinity when computing active cpus on Linux

### PR DESCRIPTION
**Pull request by dgrove-oss**
If pthread_getaffinity_np is available, then use the cpuset
of the current thread to determine the number of active cpus.

### CODE REVIEW

**Comment by MadCoder** [comment]
why is that better?

**Comment by dgrove-oss** [comment]
It gets the right answer if the program is being run under numactl with a restricted cpu set.  sysconf doesn't consider scheduler affinity.

**Comment by MadCoder** [comment]
I see, makes sense, could you please add a comment above to explain this shortly in the .c file ? because someone is bound to wonder at some point.

**Comment by dgrove-oss** [comment]
good point; added a comment & squashed commit.

**Pull request merged**
