### PR TITLE
DispatchSourceTimer: deprecate scheduleOneShot()/scheduleRepeating() …

### PR DESCRIPTION
**Pull request by ktopley-apple**
…and replace with schedule()

(Radar 30686937)

### CODE REVIEW

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by MadCoder** [comment]
@ktopley-apple what is the status of this?

**Comment by ktopley-apple** [comment]
It’s blocked on a compiler change that is scheduled to be made after WWDC.

**Comment by ktopley-apple** [comment]
This will be merged in a future darwin trunk sync.

**Pull request closed without merging**
