### PR TITLE
Remove objc_retainAutoreleasedReturnValue workaround.

### PR DESCRIPTION
**Pull request by al45tair**
The compiler has now been fixed to not generate calls to this function unless ObjC interop is enabled.

rdar://123945799

### CODE REVIEW

**Comment by al45tair** [comment]
@swift-ci test Linux platform

**Comment by al45tair** [comment]
@swift-ci test Windows platform

**Comment by al45tair** [comment]
See #72011 for the compiler fix.

**Review by compnerd — APPROVED** [review]
This is great!

**Pull request merged**
