### PR TITLE
build: improve cross-compilation for android

### PR DESCRIPTION
**Pull request by compnerd**
The sysroot headers for android require some definitions to be altered.
Ensure that we do not define `_GNU_SOURCE` for Android.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @ephemer

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@MadCoder @das okay to merge?

**Comment by johnno1962** [comment]
Hi @compnerd, I’m looking at getting the build of an android toolkit to be possible on macOS alone and am looking to move to the new cmake way of doing things. Would it be possible for you to document the command you ran for a cmake Android build on Linux here so I can adapt it for macOS. Cheers!

**Comment by johnno1962** [comment]
Is it something like:
```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/Users/user/swifty-robot-environment/util/prepare_environment/swift-source/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/clang -DCMAKE_CXX_COMPILER=/Users/user/swifty-robot-environment/util/prepare_environment/swift-source/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/clang++ -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_NDK=/usr/local/android/ndk -DENABLE_SWIFT=YES -DCMAKE_SWIFT_COMPILER=/Users/user/swifty-robot-environment/util/prepare_environment/swift-install/usr/bin/swiftc -DENABLE_TESTING=OFF -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a ../swift-corelibs-libdispatch
```

**Comment by ephemer** [comment]
@johnno1962 we spoke about this on Slack but here for anyone else wondering. This command works on both Mac and Linux:

```
cmake -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_SYSTEM_NAME=Android \
    -DCMAKE_SYSROOT=$HOME/dev/android-toolchain/sysroot \
    -DENABLE_SWIFT=YES \
    -DBUILD_SHARED_LIBS=YES \
    -DCMAKE_SWIFT_COMPILER=$SWIFT_INSTALLATION_PATH/usr/Darwin/swiftc \
    -DENABLE_TESTING=OFF \
    -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
    -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
    $SWIFT_INSTALLATION_PATH/swift-corelibs-libdispatch
```

I'm about to put another pull request through with the required changes to make that command work

**Pull request merged**
