### PR TITLE
build: switch the module map according to the target

### PR DESCRIPTION
**Pull request by compnerd**
Use a darwin specific modulemap on darwin, and the generic one
elsewhere.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @das 

Should help with the Darwin support.

**Comment by das** [comment]
makes sense, don't we have this distinction on the install path somewhere already ? (the right modulemap has to be installed as well on a per-platform basis)
they could probably shared the same variable

**Comment by compnerd** [comment]
Seems that the build use to rely on symbolic links.  Add support for doing that in the CMake build rather than the custom handling.

**Comment by das** [comment]
ok, makes sense to replicate that if that is how the existing autoconf build system was doing it, and I guess that also makes the install of the modulemap work (by copying the target of the symlink)

**Pull request merged**
