### PR TITLE
update CMake support

### PR DESCRIPTION
**Pull request by dgrove-oss**
remove libpwq support and add internal_workqueue.

also add dtrace rules to generate provider.h

### CODE REVIEW

**Comment by dgrove-oss** [comment]
@MadCoder some updates to CMake support.  We'll need more than this before we can switch over, but this was a logical first step.  This is enough to at least get building libdispatch standalone and running the tests to work after the libpwq removal.

**Comment by dgrove-oss** [comment]
Update with a number of additional fixes/tweaks so that CMake is now working nicely for me on Linux to build and test dispatch in combination with swift/utils/build-script.  @MadCoder I think this is ready to merge.   

The merge should have no actual effect (since it leaves the autoconf build in place).  Once this PR is merged, I will start submitting PRs to the other swift projects (swift, foundation, swiftpm) to incrementally switch them over to the new build system, once that is done we can finish the process by removing the autoconf-related files from libdispatch.

**Comment by das** [comment]
oops, @dgrove-oss I think I just obsoleted/conflicted some of this by merging @compnerd's #260, should have checked for older open PRs first, sorry

**Comment by das** [comment]
btw, before switching over other projects, it would be good to have the Darwin CMake build support in place so that we can test things together with other projects on Darwin also.
As mentioned in #260 I have mode some progress on that but it needs more work

**Comment by dgrove-oss** [comment]
no worries; @compnerd is better with CMake than I am.   I'll take a look and see if there are parts of this are still needed and put them in a new PR

**Pull request closed without merging**
