### PR TITLE
Revert "Revert "Remove libbsd dependency for Linux""

### PR DESCRIPTION
**Pull request by compnerd**
This reverts commit 4b87733f3e5e62a1c7a243d7e06cd35ae4b665b3.

### CODE REVIEW

**Comment by compnerd** [comment]
@benlangmuir -

```
15:30:10 FAILED: libdispatch-prefix/src/libdispatch-stamp/libdispatch-build libdispatch-prefix/lib/libdispatch.so libdispatch-prefix/lib/dispatch libdispatch-prefix/lib/libBlocksRuntime.so libdispatch-prefix/lib/BlocksRuntime 
15:30:10 cd /home/buildnode/jenkins/workspace/oss-swift-5.1-incremental-RA-linux-ubuntu-14_04/buildbot_incremental/swift-linux-x86_64/libdispatch-prefix/src/libdispatch-build && /opt/bin/cmake --build .
15:30:10 [0/1][  0%][0.000s] Re-running CMake...
```

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by benlangmuir** [comment]
Sorry for the churn.  Looks like this built fine last night on 14.04

**Comment by compnerd** [comment]
Seems that we got it merged back in quick enough, worked out just fine :-)

**Comment by ianpartridge** [comment]
Does this mean that Linux won't need the `libbsd` system package installed? If so, it would be great to get this in 5.1 so I can reduce the size of our Docker images even further. @compnerd?

**Comment by compnerd** [comment]
@ianpartridge - that is correct, Linux no longer requires the `libbsd` system package installed.  I also updated the docs to reflect that.  Also note that if you are trimming dependencies, libBlocksRuntime is no longer a dependency either.

**Comment by ianpartridge** [comment]
Awesome.

**Pull request merged**
