### PR TITLE
Added Android-specific CMake configuration.

### PR DESCRIPTION
**Pull request by vgorloff**
This PR adds missed Android specific flags to libDispatch build.
It also enables build of `libDispatch` on macOS cross-compile host using simple CMake invocation like below:

```sh
cd /[EDITED]/ToolChain/Build/aarch64/swift-corelibs-libdispatch && \
   cmake -G Ninja \
   -DCMAKE_TOOLCHAIN_FILE=/[EDITED]/ndk/build/cmake/android.toolchain.cmake \
   -DANDROID_STL=c++_static \
   -DANDROID_TOOLCHAIN=clang \
   -DANDROID_PLATFORM=android-24 \
   -DANDROID_ABI=arm64-v8a \
   -DSWIFT_ANDROID_NDK_PATH=/[EDITED]/ndk \
   -DSWIFT_ANDROID_NDK_GCC_VERSION=4.9 \
   -DSWIFT_ANDROID_API_LEVEL=24 \
   -DCMAKE_BUILD_TYPE=Release \
   -DENABLE_SWIFT=true \
   -DENABLE_TESTING=false \
   -DCMAKE_SWIFT_COMPILER="/[EDITED]/Build/darwin/swift/bin/swiftc" \
   -DCMAKE_PREFIX_PATH="/[EDITED]/Build/darwin/swift/lib/cmake/swift" \
   -DCMAKE_INSTALL_PREFIX=/ \
   /[EDITED]/Sources/swift-corelibs-libdispatch
```

### CODE REVIEW

**Comment by vgorloff** [comment]
Thanks!

I have also another variant of patch which don't have dependency on `CMAKE_TOOLCHAIN_FILE` option. Will update PR soon...

**Comment by vgorloff** [comment]
PR updated. Usage of option `-DCMAKE_TOOLCHAIN_FILE=/[EDITED]/ndk/build/cmake/android.toolchain.cmake` not needed anymore.

In order to Configure libDispatch on macOS the following command can be used:

```sh
mkdir -p "/swift-everywhere-toolchain/ToolChain/Build/darwin-x86_64/swift-corelibs-libdispatch"
cd /swift-everywhere-toolchain/ToolChain/Build/darwin-x86_64/swift-corelibs-libdispatch && \
   cmake -G Ninja \
   -DCMAKE_SYSTEM_NAME=Android \
   -DCMAKE_ANDROID_NDK=/Android/sdk/ndk-bundle \
   -DCMAKE_ANDROID_API=24 \
   -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
   -DCMAKE_C_FLAGS="-fuse-ld=gold -Wno-unused-command-line-argument -B /Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin -Wl,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/x86_64-linux-android/4.9.x,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android/24 -Wl,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/lib64" \
   -DCMAKE_CXX_FLAGS="-fuse-ld=gold -Wno-unused-command-line-argument -B /Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin -Wl,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/lib/gcc/x86_64-linux-android/4.9.x,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android/24 -Wl,-L,/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/lib64" \
   -DCMAKE_AR=/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/ar \
   -DCMAKE_LINKER=/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/ld.gold \
   -DCMAKE_RANLIB=/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/ranlib \
   -DCMAKE_STRIP=/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/strip \
   -DCMAKE_NM=/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/nm \
   -DCMAKE_OBJCOPY=/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/objcopy \
   -DCMAKE_OBJDUMP=/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/x86_64-linux-android/bin/objdump \
   -DSWIFT_ANDROID_NDK_PATH=/Android/sdk/ndk-bundle \
   -DSWIFT_ANDROID_NDK_GCC_VERSION=4.9 \
   -DSWIFT_ANDROID_API_LEVEL=24 \
   -DCMAKE_BUILD_TYPE=Release \
   -DENABLE_SWIFT=true \
   -DENABLE_TESTING=false \
   -DCMAKE_SWIFT_COMPILER="/swift-everywhere-toolchain/ToolChain/Build/darwin-host/swift/bin/swiftc" \
   -DCMAKE_PREFIX_PATH="/swift-everywhere-toolchain/ToolChain/Build/darwin-host/swift/lib/cmake/swift" \
   -DCMAKE_INSTALL_PREFIX=/ \
   /swift-everywhere-toolchain/ToolChain/Sources/swift-corelibs-libdispatch
```

In order to Build libDispatch on macOS the following command can be used:

```sh
mkdir -p "/swift-everywhere-toolchain/ToolChain/Build/darwin-x86_64/swift-corelibs-libdispatch"
ln -vfs /Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android/24/crtbegin_so.o /swift-everywhere-toolchain/ToolChain/Build/darwin-x86_64/swift-corelibs-libdispatch/src
ln -vfs /Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/x86_64-linux-android/24/crtend_so.o /swift-everywhere-toolchain/ToolChain/Build/darwin-x86_64/swift-corelibs-libdispatch/src
cd /swift-everywhere-toolchain/ToolChain/Build/darwin-x86_64/swift-corelibs-libdispatch && ninja
```

**Comment by vgorloff** [comment]
Hello,

Is PR without `android.toolchain.cmake` usage looks better or something needs to be changed?

**Comment by compnerd** [comment]
@vgorloff I would prefer that we do not merge this.  There should be no android specific parameters that libdispatch needs to add.  The linker flags are controllable via `SWIFT_LINKER_FLAGS` and the compile flags via `SWIFT_FLAGS`.  Especially with the plan being to move to CMake 3.15, you should be able to just do `CMAKE_TOOLCHAIN_FILE=` and specify the standard android flags to cmake to do the cross-compilation.

**Comment by vgorloff** [comment]
Ok. Let's wait for Cmake 3.15 support in Swift, Dispatch and Foundation.

**Pull request closed without merging**
