### PR TITLE
Add more comments for #endif in .h file.

### PR DESCRIPTION
**Pull request by lamtrinhdev**
This is a long `.h` file. I would like to are more comment for `#endif`.

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
Dear @rokhinip ,

Base on the old PR https://github.com/apple/swift-corelibs-libdispatch/pull/837 , I moved the the new PR with single commit. Please help me to review it.

Thanks,
Lam

**Review by rokhinip — APPROVED** [review]

**Comment by rokhinip** [comment]
Please kick off CI and then merge it.

**Comment by lamtrinhdev** [comment]
@swift-ci  please test

**Comment by lamtrinhdev** [comment]
Dear @rokhinip ,

I do not have permission to call @swift-ci  and merge. Could you please support me?

Thanks,
Lam

**Comment by rokhinip** [comment]
I can do that but we need to get you access if you are planning to continue contributing because I cannot be doing this for every PR you put up

**Comment by rokhinip** [comment]
@swift-ci please test

**Comment by lamtrinhdev** [comment]
Dear @rokhinip ,

I got it. Thank you for your support.

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @rokhinip ,

Could you help me to merge the PR?

Thanks,
Lam

**Pull request merged**
