### PR TITLE
added a sys/queue.h implementation for Windows

### PR DESCRIPTION
**Pull request by dplanitzer**
Added a copy of the Apple / Darwin sys/queue.h and hooked things up such that we use that one when building on Windows because the Windows SDK doesn't come with a sys/queue.h header.

### CODE REVIEW

**Comment by dplanitzer** [comment]
cc @MadCoder @compnerd

**Comment by compnerd** [comment]
Why can't we use libbsd?  I've been building against libbsd for Windows.

**Comment by adierking** [comment]
I've been working on adding Windows support to libbsd: https://gitlab.freedesktop.org/libbsd/libbsd/merge_requests/1

**Comment by tkremenek** [comment]
What precisely is the dependency here on libbsd?  Is it just to get a header, or a link dependency?  The license issue just needs to be reviewed (I can consult Apple's lawyers), but not necessarily a blocker.

**Comment by dplanitzer** [comment]
See my comment [here](https://github.com/apple/swift-corelibs-libdispatch/pull/367l). I can create an independent implementation of needed queue macros instead if that makes things simpler.

**Comment by tkremenek** [comment]
@dplanitzer I get a 404 with that link

**Comment by dplanitzer** [comment]
@MadCoder @tkremenek I've updated the PR with an independent implementation of the relevant TAILQ macros. Libdispatch only uses a handful of them anyway. I've tested the implementation locally and verified that it works beautifully :)

**Comment by MadCoder** [comment]
@swift-ci please test

**Comment by tkremenek** [comment]
@dplanitzer was the relevant implementation of `TAILQ` cribbed from the libbsd header?  If so, technically that's copyrighted and can't just be copy-and-pasted into another place.

**Comment by dplanitzer** [comment]
@tkremenek I did a new implementation from scratch based on the documentation in the man 3 queue page. It's a simple standard doubly-linked list implementation while the sys/queue.h thing does something more fancy to avoid a few if-then checks on list manipulation.

**Comment by tkremenek** [comment]
@dplanitzer OK, perfect.

**Comment by tkremenek** [comment]
I think we can merge this.

**Pull request merged**
