### PR TITLE
Fixes incorrect behavior of DispatchData.copyBytes() when the start …

### PR DESCRIPTION
**Pull request by ktopley-apple**
Fixes incorrect result of calling the DispatchData.copyBytes() method when the start index of the source range is not 0. Also fixes the behavior when the start index does not coincide with the start of a region.

Related to #7036.

rdar://problem/29005050

### CODE REVIEW

**Comment by ktopley-apple** [comment]
@swift-ci Please test

**Comment by ktopley-apple** [comment]
Updated with review comments.

**Comment by moiseev** [comment]
LGTM

**Comment by ktopley-apple** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Pull request merged**
