### PR TITLE
Android CrossCompile on Mac: Fixes Cmake error "Unrecognized architecture on host system: armv7-a"

### PR DESCRIPTION
**Pull request by vgorloff**
Hello!

This PR fixes error shown below:

```
cd $REPO/swift-everywhere-toolchain/ToolChain/Build/armv7a/swift-corelibs-libdispatch && \
cmake -G Ninja \
-DCMAKE_INSTALL_PREFIX=/ \
-DCMAKE_TOOLCHAIN_FILE=$ndk-bundle/build/cmake/android.toolchain.cmake \
-DANDROID_STL=c++_static \
-DANDROID_TOOLCHAIN=clang \
-DANDROID_PLATFORM=android-24 \
-DANDROID_ABI=armeabi-v7a \
-DCMAKE_BUILD_TYPE=Release \
-DENABLE_SWIFT=true \
-DENABLE_TESTING=false \
-DCMAKE_SWIFT_COMPILER="$REPO/swift-everywhere-toolchain/ToolChain/Build/darwin/swift/bin/swiftc" \
-DCMAKE_PREFIX_PATH="$REPO/swift-everywhere-toolchain/ToolChain/Build/darwin/swift/lib/cmake/swift" \

$REPO/swift-everywhere-toolchain/ToolChain/Sources/swift-corelibs-libdispatch
CMake Error at cmake/modules/SwiftSupport.cmake:246 (message):
  Unrecognized architecture on host system: armv7-a
Call Stack (most recent call first):
  CMakeLists.txt:59 (get_swift_host_arch)


-- Configuring incomplete, errors occurred!
```

### CODE REVIEW

**Comment by vgorloff** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @ktopley-apple

**Comment by vgorloff** [comment]
Hi,

Is it a good time to run `@swift-ci please test and merge` in order to merge this PR?

Thank you!

**Pull request merged**
