### PR TITLE
Fix libdispatch's copy of objc_retainAutoreleasedReturnValue.

### PR DESCRIPTION
**Pull request by gparker42**

### CODE REVIEW

**Comment by gparker42** [comment]
@swift-ci please test linux

**Comment by dgrove-oss** [comment]
Thanks for catching this.  Not sure how we screwed this up;  it was correct in the old Swift2 wrapping overlay but something got messed up in the big Swift3 merge.  That's also apparently when CFRuntime got changed to CFFuntime in the comment :smile:   We need a version of this change for the swift3-branch as well.

**Comment by gparker42** [comment]
@swift-ci please test linux

**Comment by gparker42** [comment]
@dgove-oss, I can't find libdispatch's Swift 3 branch. Can you cherry-pick this there?

**Comment by dgrove-oss** [comment]
sure, no problem.  I will take care of that first thing tomorrow morning.

**Comment by das** [comment]
how did we end up with no merge commit for this change on master ? was it not merged via the github interface ?

**Comment by gparker42** [comment]
I probably use rebase-and-merge. github does not introduce a merge commit with that procedure.

**Comment by das** [comment]
ok, if possible please avoid that path in the future, our import automation into the Apple-internal libdispatch repository currently relies on identifying merge commits (to match up with github PRs and their urls)

**Comment by gparker42** [comment]
IIRC you can disable rebase-and-merge in github's repository settings.

**Comment by gparker42** [comment]
https://help.github.com/articles/configuring-commit-rebasing-for-pull-requests/

**Comment by das** [comment]
cool, I'll ask the admins to do that, thanks!

**Pull request merged**
