### PR TITLE
SR-9033: handle EPOLLHUP on Linux

### PR DESCRIPTION
**Pull request by adierking**
If epoll_wait() reports EPOLLHUP, we must respond immediately and
unregister the event or else Dispatch will go into a spinloop.

This makes dispatch_io_pipe_close (#476) pass on Linux with identical
output to Darwin.

### CODE REVIEW

**Comment by adierking** [comment]
cc @compnerd @ktopley-apple @MadCoder

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
Maybe add the test from Johannes PR to this? Then we have the test and impl together?

**Comment by compnerd** [comment]
@gottesmm - I don't think that matters if we commit them at the same time.  They should remain individual commits to retain the authorship information.

**Comment by gottesmm** [comment]
@compnerd you can keep the authorship information the same and have a different committer. @adierking Can you just cherry-pick that commit into this PR and do a test and merge. Lets get this in.

**Comment by gottesmm** [comment]
I created a combined PR for this to get this going. I am going to close this to eliminate confusion.

**Comment by adierking** [comment]
Thanks - I've been busy and I haven't been able to update this.

**Pull request closed without merging**
