### PR TITLE
use /usr/bin/vi instead of /usr/share/dict/words as test input 

### PR DESCRIPTION
**Pull request by dgrove-oss**
…ilable to unblock CI work.

### CODE REVIEW

**Comment by shahmishal** [comment]
@dgrove-oss Can you please create a bug for this test, so we can enable the test in the future? 

Thanks!

```
FAIL: dispatch_io
PASS: dispatch_io_net
PASS: dispatch_select
make[4]: Entering directory `/home/buildnode/disk2/workspace/oss-swift-incremental-RA-libdispatch-linux-ubuntu-14_04/Ninja-ReleaseAssert/libdispatch-linux-x86_64/tests'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/buildnode/disk2/workspace/oss-swift-incremental-RA-libdispatch-linux-ubuntu-14_04/Ninja-ReleaseAssert/libdispatch-linux-x86_64/tests'
============================================================================
Testsuite summary for libdispatch 1.3
============================================================================
# TOTAL: 26
# PASS:  25
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by MadCoder** [comment]
we just need "a large file" could you instead use a file that is here on any distribution that is large enough? /bin/systemctl is 500K /usr/bin/vi is probably also always here and in the MB range

disabling test is wrong

**Comment by dgrove-oss** [comment]
Sure.  I can write the tests to look for different files instead.   I've got the configure check working, so I will probably keep it and check for different input files.    While we're playing with this, dispatch_io also wants another file (but skips the test without failing if it isn't there): 

```
#if TARGET_OS_EMBEDDED
#define LARGE_FILE "/System/Library/Fonts/Cache/STHeiti-Light.ttc" // 29MB file
#define maxopenfiles 768
#else
#define LARGE_FILE "/System/Library/Speech/Voices/Alex.SpeechVoice/Contents/Resources/PCMWave" // 417MB file
#define maxopenfiles 4096
#endif
```

Suggestions for a replacement file here that will likely be on a distro?

**Comment by parkera** [comment]
Can't we just create a file in a temporary directory?

**Comment by dgrove-oss** [comment]
I'm taking Pierre's suggestion and using /usr/bin/vi as the input file instead.  The configure check is probably overkill.  Will push an update in a couple of minutes (testing it locally not).

**Comment by parkera** [comment]
@swift-ci please test linux

**Comment by shahmishal** [comment]
@swift-ci please test linux

**Comment by shahmishal** [comment]
```
Build timed out (after 166 minutes). Marking the build as failed.
Build was aborted
```

**Comment by seabaylea** [comment]
The fail was in the dispatch_pingpong test, so not related to this change.

Below is the output of the test log file:

```
==================================================
[TEST] Dispatch Ping Pong
[PID] 32399
==================================================


[BEGIN] dispatch_queue_create(ping)
	Actual: 0x1b50c40
	Expected: 0x1b50c40
[PASS] dispatch_queue_create(ping)

[BEGIN] dispatch_queue_create(pong)
	Actual: 0x1b50cf0
	Expected: 0x1b50cf0
[PASS] dispatch_queue_create(pong)

[BEGIN] dispatch_group_create
	Actual: 0x1b50d80
	Expected: 0x1b50d80
[PASS] dispatch_group_create

[BEGIN] Process exited
	Actual: 1
	Expected: 0
[FAIL] Process exited (bsdtestharness.c:132)
	bsdtestharness.c:132
[PERF]	wall time: 0.000100
[PERF]	user time: 0.068000
[PERF]	system time: 0.004000
[PERF]	max resident set size: 17580
[PERF]	page faults: 0
[PERF]	swaps: 0
[PERF]	voluntary context switches: 44
[PERF]	involuntary context switches: 10
FAIL dispatch_pingpong (exit status: 1)
```

**Comment by dgrove-oss** [comment]
is there something different in the build machines, the steps taken to build/test or the environment for testing pull requests against dispatch vs. the other CI testing that includes building & testing dispatch on Linux?   A couple of the recent dispatch pull requests have failed by hanging while running dispatch_pingpong, but as far as I know we've never seen that hang happen in other CI configurations with dispatch and I can't reproduce it locally.

**Comment by seabaylea** [comment]
I've seen the `dispatch_pingpong` failure maybe twice in the wider libdispatch CI.  The CI env is running with 48 CPUs, which is a little larger than I have locally - that might be part of the issue.

**Comment by parkera** [comment]
Any update here @seabaylea or @dgrove-oss? We're still blocked on merging URLSession because dispatch tests aren't passing.

**Comment by parkera** [comment]
I want to see if this fails again in the same way.

**Comment by parkera** [comment]
@swift-ci test linux

**Comment by seabaylea** [comment]
This one should be good - we've got a couple of other failures though. I'm currently looking at those.

**Comment by parkera** [comment]
I'm going to merge this. We will put up a different PR to disable the pingpong test, so as to make some forward progress here.

**Pull request merged**
