### PR TITLE
Correct the Xcode fixits for dispatch_async() and dispatch_group_async()

### PR DESCRIPTION
**Pull request by ktopley-apple**
The same change was already made in the swift repo (https://github.com/apple/swift/pull/6958)

rdar://problem/27915073

### CODE REVIEW

**Comment by ktopley-apple** [comment]
@swift-ci Please test

**Comment by ktopley-apple** [comment]
Test failure is unrelated to this change.

**Comment by ktopley-apple** [comment]
@swift-ci Please test

**Comment by ktopley-apple** [comment]
@dgrove-oss could you please take a look at the build output for Linux? It's failing with a timeout in the SwiftPM tests.

**Comment by dgrove-oss** [comment]
I think there is something broken in how the libdispatch PR testing is being done.  It has been habitually failing on this swiftPM subtest (and we have been ignoring the failure, merging the changes, and not seeing the failure in the main runs).    I'll ask for help on swift-dev list to see if anyone has an idea of what could be wrong.

**Comment by ktopley-apple** [comment]
@dgrove-oss thanks. The failure is clearly not related to the change, so I am going to go ahead and merge.

**Pull request merged**
