### PR TITLE
Merge darwin/libdispatch-913.1.4 to master

### PR DESCRIPTION
**Pull request by das**
Merge tag darwin/libdispatch-913.1.4 on darwin/trunk.

This includes the latest Apple source drop libdispatch-913.1.4 (up from libdispatch-890 in #254), on top of darwin/darwin-009.

The latter tag includes the github PR's below merged to trunk that we've pulled back into the Apple internal repository, along with any changes made to them during internal review and testing on Darwin:

#249 from dgrove-oss/update-docs
#248 from dgrove-oss/queue_config_cleanup
#254 from apple/das-darwin-libdispatch-890-merge-master
#256 from apple/revert-255-revert-254-das-darwin-libdispatch-890-merge-master
#172 from karwa/removespecific
#253 from dgrove-oss/linux-qos-prioritty
#259 from johnno1962a/master
#260 from compnerd/cmake-parity
#261 from compnerd/module-maps
#262 from compnerd/gold
#264 from compnerd/dtrace-usdt-probes
#266 from compnerd/pwq
#258 from spevans/pr_expose_symbol
#267 from dgrove-oss/cmake-copy-libdisaptch
#269 from dgrove-oss/cmake-default-args
#268 from ktopley-apple/dispatch-sync-fixup-overlay
#277 from apple/mad/remove-sys-membarrier
#280 from apple/mad/epoll-fixes
#281 from apple/mad/epoll-fixes-2
#279 from apple/mad/greedy-signalfd
#273 from dgrove-oss/match-darwin-cflags-round1

### CODE REVIEW

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
with those last two changes, the CI is happy.

@dgrove-oss would you mind giving this a manual sanity check on your end as well just to make sure we don't break anything at this late stage ?

**Comment by dgrove-oss** [comment]
sure.  i'll do that this morning.

**Comment by das** [comment]
Thanks Dave!

**Pull request merged**
