### PR TITLE
Fixed printf format macro for intptr_t arguments.

### PR DESCRIPTION
**Pull request by triplef**
Was using PRId64 instead of PRIdPTR, which would be incorrect when compiling for 32-bit.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by triplef** [comment]
It seems that the test failed due to the following error, which seems unrelated to this change:
```
23:31:42 CMake Error at CMakeLists.txt:25 (message):
23:31:42   ICU version 55.1 is less than required version 61
```

Is there anything I can do to make this pass?

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by triplef** [comment]
This time a number of tests in Foundation failed, which again seem completely unrelated to this change. @compnerd any idea? Thanks!

**Comment by compnerd** [comment]
mmm...that does go through libdispatch, so it could be a difference, if you can find the failure in the logs, it would be helpful.

**Comment by triplef** [comment]
There seem to be a couple of errors / failures, none of which seem to me to be related to my changes in `_dispatch_semaphore_debug()` and `_dispatch_group_debug()`. Please let me know if there’s anything else I can do to resolve this.

First, there is this error in "Performing configure step for 'compiler-rt'":

```
19:38:53 -- Looking for unwind.h
19:38:54 -- Looking for unwind.h - found
19:38:54 
 
llvm-config: error: component libraries and shared library
19:38:54 
19:38:54 llvm-config: error: missing: /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/buildbot_linux/llvm-linux-x86_64/lib/libLLVMTestingSupport.a
19:38:54 CMake Warning at cmake/Modules/CompilerRTUtils.cmake:263 (message):
19:38:54   llvm-config finding testingsupport failed with status 1
19:38:54 Call Stack (most recent call first):
19:38:54   CMakeLists.txt:69 (load_llvm_config)
19:38:54 
19:38:54 
19:38:54 -- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
```

And then a number of tests fail:

#### TestDateIntervalFormatter
```
20:10:48 Test Suite 'TestDateIntervalFormatter' started at 2019-02-28 13:10:13.286
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeBillionSeconds' started at 2019-02-28 13:10:13.286
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:44: error: TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeBillionSeconds : XCTAssertTrue failed - String 'January 1, 2001, 12:00:00 AM GMT â January 25, 2096, 5:20:00 AM GMT' (must end with: false) does not contain in sequence: ["January 1", "2001", "12:00:00 AM", "Greenwich Mean Time", "January 25", "2096", "5:20:00 AM", "Greenwich Mean Time"] â reason: missed("Greenwich Mean Time")
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeBillionSeconds' failed (0.002 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeMillionSeconds' started at 2019-02-28 13:10:13.287
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:44: error: TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeMillionSeconds : XCTAssertTrue failed - String 'January 1, 2001, 12:00:00 AM GMT â February 4, 2001, 5:20:00 PM GMT' (must end with: false) does not contain in sequence: ["January 1", "2001", "12:00:00 AM", "Greenwich Mean Time", "February 4", "2001", "5:20:00 PM", "Greenwich Mean Time"] â reason: missed("Greenwich Mean Time")
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeMillionSeconds' failed (0.001 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeBillionSecondsReversed' started at 2019-02-28 13:10:13.289
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:44: error: TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeBillionSecondsReversed : XCTAssertTrue failed - String 'January 25, 2096, 5:20:00 AM GMT â January 1, 2001, 12:00:00 AM GMT' (must end with: false) does not contain in sequence: ["January 25", "2096", "5:20:00 AM", "Greenwich Mean Time", "January 1", "2001", "12:00:00 AM", "Greenwich Mean Time"] â reason: missed("Greenwich Mean Time")
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeBillionSecondsReversed' failed (0.001 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeMillionSecondsReversed' started at 2019-02-28 13:10:13.290
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:44: error: TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeMillionSecondsReversed : XCTAssertTrue failed - String 'February 4, 2001, 5:20:00 PM GMT â January 1, 2001, 12:00:00 AM GMT' (must end with: false) does not contain in sequence: ["February 4", "2001", "5:20:00 PM", "Greenwich Mean Time", "January 1", "2001", "12:00:00 AM", "Greenwich Mean Time"] â reason: missed("Greenwich Mean Time")
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossThreeMillionSecondsReversed' failed (0.001 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToSameDate' started at 2019-02-28 13:10:13.292
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:44: error: TestDateIntervalFormatter.testStringFromDateToSameDate : XCTAssertTrue failed - String 'February 4, 2001, 5:20:00 PM GMT' (must end with: true) does not contain in sequence: ["February 4", "2001", "5:20:00 PM", "Greenwich Mean Time"] â reason: missed("Greenwich Mean Time")
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToSameDate' failed (0.001 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateIntervalAcrossThreeMillionSeconds' started at 2019-02-28 13:10:13.293
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:44: error: TestDateIntervalFormatter.testStringFromDateIntervalAcrossThreeMillionSeconds : XCTAssertTrue failed - String 'January 1, 2001, 12:00:00 AM GMT â February 4, 2001, 5:20:00 PM GMT' (must end with: false) does not contain in sequence: ["January 1", "2001", "12:00:00 AM", "Greenwich Mean Time", "February 4", "2001", "5:20:00 PM", "Greenwich Mean Time"] â reason: missed("Greenwich Mean Time")
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateIntervalAcrossThreeMillionSeconds' failed (0.001 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossOneWeek' started at 2019-02-28 13:10:13.295
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossOneWeek' passed (0.002 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossSixtyDays' started at 2019-02-28 13:10:13.296
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossSixtyDays' passed (0.001 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossFiveHours' started at 2019-02-28 13:10:13.298
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:199: error: TestDateIntervalFormatter.testStringFromDateToDateAcrossFiveHours : XCTAssertNil failed: "Index(_rawBits: 2424832)..<Index(_rawBits: 2883584)" - 
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:44: error: TestDateIntervalFormatter.testStringFromDateToDateAcrossFiveHours : XCTAssertTrue failed - String 'January 1, 2001, 10:00:00 PM GMT â January 2, 2001, 3:00:00 AM GMT' (must end with: true) does not contain in sequence: ["January", "1", "2001", "10:00:00 PM", "Greenwich Mean Time", "January", "2", "2001", "3:00:00 AM", "Greenwich Mean Time"] â reason: missed("Greenwich Mean Time")
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossFiveHours' failed (0.002 seconds)
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossEighteenHours' started at 2019-02-28 13:10:13.300
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestDateIntervalFormatter.swift:221: error: TestDateIntervalFormatter.testStringFromDateToDateAcrossEighteenHours : XCTAssertNil failed: "Index(_rawBits: 2424832)..<Index(_rawBits: 2883584)" - 
20:10:48 Test Case 'TestDateIntervalFormatter.testStringFromDateToDateAcrossEighteenHours' failed (0.001 seconds)
20:10:48 Test Suite 'TestDateIntervalFormatter' failed at 2019-02-28 13:10:13.301
20:10:48 	 Executed 10 tests, with 9 failures (0 unexpected) in 0.016 (0.016) seconds
```

#### TestNSNumber.test_descriptionWithLocale
```
20:10:48 Test Case 'TestNSNumber.test_descriptionWithLocale' started at 2019-02-28 13:10:18.599
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSNumber.swift:1144: error: TestNSNumber.test_descriptionWithLocale : XCTAssertEqual failed: ("2.2250738585072E-308") is not equal to ("2.225073858507201E-308") - 
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSNumber.swift:1145: error: TestNSNumber.test_descriptionWithLocale : XCTAssertEqual failed: ("4.94065645841247E-324") is not equal to ("5E-324") - 
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSNumber.swift:1146: error: TestNSNumber.test_descriptionWithLocale : XCTAssertEqual failed: ("1.79769313486232E+308") is not equal to ("1.797693134862316E+308") - 
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSNumber.swift:1188: error: TestNSNumber.test_descriptionWithLocale : XCTAssertEqual failed: ("2,2250738585072E-308") is not equal to ("2,225073858507201E-308") - 
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSNumber.swift:1189: error: TestNSNumber.test_descriptionWithLocale : XCTAssertEqual failed: ("4,94065645841247E-324") is not equal to ("5E-324") - 
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSNumber.swift:1190: error: TestNSNumber.test_descriptionWithLocale : XCTAssertEqual failed: ("1,79769313486232E+308") is not equal to ("1,797693134862316E+308") - 
20:10:48 Test Case 'TestNSNumber.test_descriptionWithLocale' failed (0.003 seconds)
20:10:48 Test Case 'TestNSNumber.test_objCType' started at 2019-02-28 13:10:18.602
20:10:48 Test Case 'TestNSNumber.test_objCType' passed (0.0 seconds)
20:10:48 Test Case 'TestNSNumber.test_stringValue' started at 2019-02-28 13:10:18.602
20:10:48 Test Case 'TestNSNumber.test_stringValue' passed (0.0 seconds)
20:10:48 Test Case 'TestNSNumber.test_Equals' started at 2019-02-28 13:10:18.602
20:10:48 Test Case 'TestNSNumber.test_Equals' passed (0.0 seconds)
20:10:48 Test Case 'TestNSNumber.test_boolValue' started at 2019-02-28 13:10:18.602
20:10:48 Test Case 'TestNSNumber.test_boolValue' passed (0.0 seconds)
20:10:48 Test Case 'TestNSNumber.test_hash' started at 2019-02-28 13:10:18.602
20:10:48 Test Case 'TestNSNumber.test_hash' passed (0.0 seconds)
20:10:48 Test Suite 'TestNSNumber' failed at 2019-02-28 13:10:18.602
20:10:48 	 Executed 27 tests, with 6 failures (0 unexpected) in 0.004 (0.004) seconds
```

#### TestScanner.testScanXXX
```
20:10:48 Test Case 'TestScanner.testScanCharacter' started at 2019-02-28 13:10:21.816
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanCharacter : XCTAssertEqual failed: ("Optional("ð©â")") is not equal to ("Optional("ð©âð©âð§âð§")") - Scan single grapheme (made of multiple code points)
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:156: error: TestScanner.testScanCharacter : XCTAssertTrue failed - At end (ignores trailing whitespace)
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanCharacter : XCTAssertEqual failed: ("Optional("ð§â")") is not equal to ("Optional("ð§ââï¸")") - Scan single grapheme (made of multiple code points)
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:156: error: TestScanner.testScanCharacter : XCTAssertTrue failed - At end (ignores trailing whitespace)
20:10:48 Test Case 'TestScanner.testScanCharacter' failed (0.0 seconds)
20:10:48 Test Case 'TestScanner.testScanString' started at 2019-02-28 13:10:21.816
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanString : XCTAssertEqual failed: ("Optional("Lily is a ð©ð»â")") is not equal to ("nil") - New method must not split graphemes while scanning
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanString : XCTAssertEqual failed: ("nil") is not equal to ("Optional("Lily is a ð©ð»âð»")") - New method must work if graphemes would not be split while scanning
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:156: error: TestScanner.testScanString : XCTAssertTrue failed - After scanning the last grapheme, we are at end
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanString : XCTAssertEqual failed: ("ð»!") is not equal to ("!") - The index to scan from is the one after the end of the grapheme
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanString : XCTAssertEqual failed: ("nil") is not equal to ("Optional("!")") - Scanning starts correctly from there
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanString : XCTAssertEqual failed: ("Index(_rawBits: 1376256)") is not equal to ("Index(_rawBits: 1638400)") - The Swift.String.Index we will resume scanning from for new methods is correctly pointing to the end of the string
20:10:48 Test Case 'TestScanner.testScanString' failed (0.001 seconds)
20:10:48 Test Case 'TestScanner.testScanUpToString' started at 2019-02-28 13:10:21.817
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanUpToString : XCTAssertEqual failed: ("Optional("Lily is a ")") is not equal to ("Optional("Lily is a ð©ð»âð» NOT FOUND")") - New method must go past graphemes that match part of the scan-up-to string while scanning
20:10:48 Test Case 'TestScanner.testScanUpToString' failed (0.0 seconds)
20:10:48 Test Case 'TestScanner.testScanCharactersFromSet' started at 2019-02-28 13:10:21.817
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanCharactersFromSet : XCTAssertEqual failed: ("Optional("Lily is a ð©")") is not equal to ("Optional("Lily is a ")") - Cannot scan a grapheme that contains one or more code points not in the set
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanCharactersFromSet : XCTAssertEqual failed: ("Optional("Lily is a ð©")") is not equal to ("Optional("Lily is a ")") - Cannot scan a grapheme that contains one or more code points not in the set
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanCharactersFromSet : XCTAssertEqual failed: ("Optional("Lily is a ð©ð»â")") is not equal to ("Optional("Lily is a ")") - Cannot scan a grapheme that contains one or more code points not in the set
20:10:48 Test Case 'TestScanner.testScanCharactersFromSet' failed (0.0 seconds)
20:10:48 Test Case 'TestScanner.testScanUpToCharactersFromSet' started at 2019-02-28 13:10:21.817
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanUpToCharactersFromSet : XCTAssertEqual failed: ("Optional("Lily is a ")") is not equal to ("Optional("Lily is a ð©ð»âð» NOT FOUND")") - New method must go past graphemes that match part of the scan-up-to string while scanning
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanUpToCharactersFromSet : XCTAssertEqual failed: ("Optional("Lily is a ")") is not equal to ("Optional("Lily is a ð©ð»âð» NOT FOUND")") - New method must go past graphemes that match part of the scan-up-to string while scanning
20:10:48 /home/buildnode/jenkins/workspace/swift-corelibs-libdispatch-PR-Linux/swift-corelibs-foundation/TestFoundation/Utilities.swift:164: error: TestScanner.testScanUpToCharactersFromSet : XCTAssertEqual failed: ("Optional("Lily is a ")") is not equal to ("Optional("Lily is a ð©ð»âð» NOT FOUND")") - New method must go past graphemes that match part of the scan-up-to string while scanning
20:10:48 Test Case 'TestScanner.testScanUpToCharactersFromSet' failed (0.0 seconds)
20:10:48 Test Suite 'TestScanner' failed at 2019-02-28 13:10:21.818
20:10:48 	 Executed 10 tests, with 17 failures (0 unexpected) in 0.003 (0.003) seconds
```

In the end it looks like these cause "TestFoundation.xctest" to fail:
```
20:10:48 Test Suite 'TestFoundation.xctest' failed at 2019-02-28 13:10:48.116
20:10:48 	 Executed 1466 tests, with 32 failures (0 unexpected) in 37.69 (37.69) seconds
20:10:48 Test Suite 'All tests' failed at 2019-02-28 13:10:48.117
20:10:48 	 Executed 1466 tests, with 32 failures (0 unexpected) in 37.69 (37.69) seconds
20:10:48 
20:10:48 
20:10:48 0% tests passed, 1 tests failed out of 1
20:10:48 
20:10:48 Total Test time (real) =  37.83 sec
20:10:48 
20:10:48 The following tests FAILED:
20:10:48 	  1 - TestFoundation (Failed)
20:10:48 Errors while running CTest
20:10:48 FAILED: CMakeFiles/test.util 
```

**Comment by compnerd** [comment]
The compiler-rt thing is not important.  The TestFoundation failure is however.  I didn't manage to spot the test that failed.  It doesn't seem like it failed due to a segfault though.

**Comment by triplef** [comment]
These are the tests that failed:

* TestDateIntervalFormatter
* TestNSNumber.test_descriptionWithLocale
* TestScanner.testScan... (various tests)

I also saw that #451 has the same tests failing, which seems like further indication that this a different issue with the tests.

**Comment by compnerd** [comment]
This sounds like an issue with ICU.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by triplef** [comment]
I’ve updated the patch to be based on the latest changes after the merge.

**Comment by millenomi** [comment]
@swift-ci please test

**Pull request merged**
