### PR TITLE
[Overlay/Queue]: Allow setting an optional  value in setSpecific

### PR DESCRIPTION
**Pull request by karwa**
Otherwise you can never clear anything you set

### CODE REVIEW

**Comment by MadCoder** [comment]
that is fairly reasonable but isn't this ABI breaking? @mwwa please review wrt this, I agree the patch makes sense and is useful.

**Comment by mwwa** [comment]
At this point I think this would need to be introduced as ```clearSpecific<T>(key:)``` so that we don't change the signature of ```setSpecific<T>(key:value:)```

**Comment by karwa** [comment]
Urgh, it's disappointing that we're at that stage so early that we have to introduce new functions to patch flaws in existing ones.

Alternatively, we could add a DispatchSpecific subscript on DidpatchQueue which allows setting nil (IIRC we can have generic subscripts, but I may be wrong)

**Comment by karwa** [comment]
What I mean to say by that is: I wasn't aware binary compatibility was a concern for Swift 3. That's supposed to be the focus of Swift 4 stage 1, as I understand it.

**Comment by mwwa** [comment]
It's not a binary compatibility issue, it's a source compatibility problem if people have to change the signatures of their existing uses in order to be able to compile.

**Comment by karwa** [comment]
@mwwa Is it actually source-breaking? Swift automatically wraps types as optionals, so any code which used the non-optional setter will continue to compile.

Also, this is technically a memory leak. I just encountered it in my app - thousands of DispatchSpecificKey allocations being left behind because something in Dispatch is retaining them (and can't be cleared). Each is 32 bytes so you lose 1K from just 32 of them. This is in a reasonably memory-constrained environment.

**Comment by karwa** [comment]
@MadCoder can we make any progress on this? As I mentioned it shouldn't be source-breaking (although the symbol would change, so it is ABI-breaking)

**Comment by mwwa** [comment]
Good point with the source compat. That looks ok then. This needs to be cloned for the mainline Dispatch overlay too (in the apple/swift repo).

@swift-ci please test.

**Comment by karwa** [comment]
I think the Foundation test has been fixed now. Can we run it again?

**Comment by parkera** [comment]
@swift-ci please test

**Comment by karwa** [comment]
huh, ¯\_(ツ)_/¯

Foundation contains a grand total of one (1) `DispatchSpecificKey`, on `NSOperation`. It's never referenced anywhere else, and `NSOperation` is never referenced from any other types in Foundation. So I'm pretty sure this change didn't break anything.

**Comment by karwa** [comment]
I don't know why the test is failing (some assertion failure in kqueue), but I'm sure this patch has nothing to do with it.

**Comment by karwa** [comment]
Can we test this again? I'd like to try get it in for the 3.1 branch date

**Comment by karwa** [comment]
Ping? This has already been merged in the Darwin SDK overlay.

**Comment by das** [comment]
@swift-ci please test

**Comment by das** [comment]
tests pass, so lets cleanup this discrepancy for 4.0

**Pull request merged**
