### PR TITLE
build: fix clang-cl exception flags

### PR DESCRIPTION
**Pull request by adierking**
When building with clang-cl, we currently pass the `/EHsc-` flag in an attempt to disable exceptions, but this is equivalent to `/EHs` which still enables C++ exceptions and trips the `#error` in block.cpp. clang-cl actually disables exceptions by default, so we don't need to pass anything.

See https://msdn.microsoft.com/en-us/library/1deeycx5.aspx.

### CODE REVIEW

**Comment by adierking** [comment]
cc @compnerd

**Comment by compnerd** [comment]
CC @madcoder

**Comment by compnerd** [comment]
@swift-could please test

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
