### PR TITLE
use reserved spelling for inline assembly

### PR DESCRIPTION
**Pull request by compnerd**
Use the reserved spelling for `asm` as it is a non-standard compiler
extension.  NFC.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @MadCoder @das @parkera

**Comment by parkera** [comment]
Seems fine to me but @MadCoder and @das should be the ones to approve in this repository.

**Comment by compnerd** [comment]
@MadCoder updated to use `__asm__ __volatile__` for the non-label cases.  I've merged the prefix change as well.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Actually, let me merge in the reserved spelling for `__typeof__` as well.  Sorry, I have a number of patches that I've had laying around that I'm trying to get through.  These are all intended to help setup everything to revive the Windows port.

**Comment by MadCoder** [comment]
this is fine :)

**Comment by MadCoder** [comment]
@swift-ci please test

**Comment by MadCoder** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@MadCoder anything else for this change or good to merge?

**Pull request merged**
