### PR TITLE
Optimize _dispatch_alloc_maybe_madvise_page

### PR DESCRIPTION
**Pull request by AtariDreams**
There is no reason to have last_locked be signed. Also, redundant checks were optimized away near the end of the function.

### CODE REVIEW

**Comment by AtariDreams** [comment]
@swift-ci please test

**Comment by AtariDreams** [comment]
cc @compnerd

**Comment by AtariDreams** [comment]
cc @drexin

**Review by etcwilde — APPROVED** [review]
These changes look fine to me.
I would still wait for another reviewer's response as I'm not super familiar with this codebase.

**Comment by rokhinip** [comment]
The older code reads cleaner to me actually - this change seems to add more branches and code repetition

**Comment by AtariDreams** [comment]
Yeah but the check is redundant knowing that when it is greater than 1, it is not 0. I could refactor it though

**Comment by AtariDreams** [comment]
Refactored. Hopefully it isn't as bad now

**Comment by etcwilde** [comment]
Quickly looking at the optimized output, the instruction sequences look the same on first glance for all three cases. I agree with @rokhinip that the original was the easiest to read so lets stay with that.
https://godbolt.org/z/e81fh5G37

I'm fine with the change to using the unsigned int though.

**Comment by AtariDreams** [comment]
All fixed!

**Comment by AtariDreams** [comment]
> Quickly looking at the optimized output, the instruction sequences look the same on first glance for all three cases. I agree with @rokhinip that the original was the easiest to read so lets stay with that.
> https://godbolt.org/z/e81fh5G37
> 
> I'm fine with the change to using the unsigned int though.

Addressed!

**Comment by AtariDreams** [comment]
> Quickly looking at the optimized output, the instruction sequences look the same on first glance for all three cases. I agree with @rokhinip that the original was the easiest to read so lets stay with that.
> https://godbolt.org/z/e81fh5G37
> 
> I'm fine with the change to using the unsigned int though.

Actually, dothing3 is the odd one out in terms of the generated assembly, being smaller and shorter

**Comment by etcwilde** [comment]
So, number 3 has fewer instructions, yes, but also involves more control flow from a readability perspective.
I haven't run any perf numbers, but statically, it looks like a difference of 4 instructions between the two.
Without a profile demonstrating how much time is saved by these, I would push for making the code more readable over reducing instructions.

**Comment by AtariDreams** [comment]
Alright. I removed the change

**Comment by AtariDreams** [comment]
@swift-ci please test

**Comment by rokhinip** [comment]
What is the problem you're trying to address here @AtariDreams? Refactors are well and good but what purpose does this serve?

**Comment by AtariDreams** [comment]
> What is the problem you're trying to address here @AtariDreams? Refactors are well and good but what purpose does this serve?

better readability and code generation

**Comment by rokhinip** [comment]
> better readability and code generation

I don't see how this change does that. I think this change adds more churn than benefit. I'd like for us to drop this change please. Thanks.

**Pull request closed without merging**
