### PR TITLE
io: use posix_fadvise() instead of readahead()

### PR DESCRIPTION
**Pull request by adierking**
readahead() is a Linux-specific system call, and many C libraries (e.g.
Android's Bionic) do not declare it by default. A more-portable alternative is
to use posix_fadvise() with `POSIX_FADV_WILLNEED`. This is functionally
equivalent to readahead() on Linux.

Additionally, on FreeBSD, Dispatch is currently using fcntl() with `F_RDAHEAD`.
This is not exactly equivalent to Darwin's `F_RDADVISE`. Using posix_fadvise()
should work better here too.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
I think that this is the right approach to make this more portable.  Any opinions @MadCoder or @parkera?

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@MadCoder  - okay to merge?

**Comment by compnerd** [comment]
@ktopley-apple - okay to merge this as well?

**Pull request merged**
