### PR TITLE
build: port to new Swift support

### PR DESCRIPTION
**Pull request by compnerd**
This ports the libdispatch build to use the new builtin Swift support in
CMake. It allows for a significant clean up of the build rules.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with the following PRs:
apple/swift#27245

@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27271

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27271

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27271

@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#2519

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#2519

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#2519
apple/swift-corelibs-xctest#285

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#2519
apple/swift-corelibs-xctest#285
apple/swift-package-manager#2352

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#2519
apple/swift-corelibs-xctest#285
apple/swift-package-manager#2352

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-foundation#2519
apple/swift-corelibs-xctest#285
apple/swift-package-manager#2352

@swift-ci please test

**Comment by compnerd** [comment]
@ktopley-apple - okay to merge?  (I'm going to wait until apple/swift#27372 is green though)

**Comment by shahmishal** [comment]
Swift CI is checking out tag `v3.15.0`, is it possible to change the min requirement to `3.15.0` compare to `3.15.1`? 

https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-14_04-long-test/7178/console

```
10:16:05 CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
10:16:05   CMake 3.15.1 or higher is required.  You are running version 3.15.0
10:16:05 
10:16:05 
10:16:05 -- Configuring incomplete, errors occurred!
```

**Pull request merged**
