### PR TITLE
Adding DISPATCH_SOURCE_TYPE_DATA_REPLACE to the Swift overlay

### PR DESCRIPTION
**Pull request by ktopley-apple**
(Radar rdar://problem/30518517)

### CODE REVIEW

**Comment by ktopley-apple** [comment]
@swift-ci please smoke test

**Comment by moiseev** [comment]
@swift-ci Please test

**Comment by ktopley-apple** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Pull request merged**
