### PR TITLE
Track armed events in muxnotes closely

### PR DESCRIPTION
**Pull request by MadCoder**
This fixes issues around resuming or re-registering file-descriptors with
a previously triggered EPOLLONESHOT event.

Signed-off-by: Pierre Habouzit <phabouzit@apple.com>
Fixes: SR-5759

### CODE REVIEW

**Comment by MadCoder** [comment]
@swift-ci please test

**Comment by MadCoder** [comment]
I'd appreciate a review from someone, @weissi (who is on vacation atm) has indepdently checked that it fixes SR-5759 for him.

the problem with epoll is that what is two different filters in the kevent world (EVFILT_READ/EVFILT_WRITE) is really a single one in epoll.

the multiplexing code which is a simplified version of the kevent one assumes that the first source that is resumed, resumes the multiplexing note, and that delivery disables it fully. However this is not quite how it works, we need to be able to do partial resumes/disarm of EPOLLIN and EPOLLOUT independently as all write sources of a given fd could be suspended while read sources are active and vice versa.

**Comment by MadCoder** [comment]
Note: this is slated for swift4 too

**Comment by dgrove-oss** [comment]
was out on vacation last week; will take a look at this tomorrow (unburying from other stuff today).  Sorry for the delay.

**Comment by MadCoder** [comment]
@dgrove-oss no worries, this isn't even a day old ;) I'll wait for you to have a look then.

**Pull request merged**
