### PR TITLE
Revert "Revert "build: port to new Swift support""

### PR DESCRIPTION
**Pull request by compnerd**
This reverts commit 91c435e9de559215cca35e4085f1e5711d09a01f.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @shahmishal

**Comment by shahmishal** [comment]
https://github.com/apple/swift-corelibs-libdispatch/pull/527

**Comment by compnerd** [comment]
oh, awesome, thanks!

**Pull request closed without merging**
