### PR TITLE
Switching back _dispatch_operation_perform to use posix_memalign from aligned_malloc

### PR DESCRIPTION
**Pull request by PriyaAvhad**
This was caught by thread sanitizer.

### CODE REVIEW

**Comment by PriyaAvhad** [comment]
@swift-ci test

**Comment by PriyaAvhad** [comment]
@swift-ci please smoke test

**Comment by PriyaAvhad** [comment]
@swift-ci test linux

**Comment by finagolfin** [comment]
Sorry, only seeing this now. I will add this commit to #827 if and when you get this merged.

**Review by rokhinip — APPROVED** [review]

**Comment by finagolfin** [comment]
@PriyaAvhad, this pull will need to be rebased before it can be merged.

**Comment by ktoso** [comment]
Needs a rebase but lgtm

**Review by ktoso — APPROVED** [review]

**Comment by finagolfin** [comment]
@PriyaAvhad, does #805 need to be reverted or is this one change enough?

**Comment by PriyaAvhad** [comment]
The thread sanitizer complaint was about just the file I have modified in this PR; but, I agree with you that it would be much cleaner to revert #805 instead.

**Comment by PriyaAvhad** [comment]
@swift-ci test

**Comment by PriyaAvhad** [comment]
@swift-ci please smoke test

**Comment by PriyaAvhad** [comment]
@swift-ci test linux

**Comment by finagolfin** [comment]
OK, if you're going to do that, then there's no need for my #826 changes for the 6.0 branch.

Just don't forget to submit this revert to the 6.0 branch next. 😉

**Comment by PriyaAvhad** [comment]
Will do. Thanks!

**Pull request merged**
