### PR TITLE
Use numericCast() to get the correct type when creating a dispatch_bl…

### PR DESCRIPTION
**Pull request by ktopley-apple**
…ock_flags_t.

rdar://problem/44957560

### CODE REVIEW

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by gottesmm** [comment]
@ktopley-apple swift-ci is down now. Check ci.swift.org.

**Comment by jrose-apple** [comment]
\*sigh\* Sure, I guess.

**Comment by ktopley-apple** [comment]
> @ktopley-apple swift-ci is down now. Check ci.swift.org.

Thanks. I was wondering what the delay was.

**Comment by ktopley-apple** [comment]
> *sigh* Sure, I guess.

I wish there were a better way. So far, we haven't been able to find one.

**Comment by ktopley-apple** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@ktopley-apple sorry CI is offline right now.

**Comment by ktopley-apple** [comment]
> @ktopley-apple sorry CI is offline right now.



> @ktopley-apple sorry CI is offline right now.

It went down again? Any ETA for return?

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
It's back online

**Comment by compnerd** [comment]
Hmm, actually, this is interesting, I am seeing a failure with this change:
https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=303

```swift-corelibs-libdispatch/src/swift/Block.swift:43:39: error: global function 'numericCast' requires that 'dispatch_block_flags_t' conform to 'BinaryInteger'
                let flags: dispatch_block_flags_t = numericCast(flags.rawValue)
                                                     ^
```

**Comment by compnerd** [comment]
I really don't understand how this is broken.  `flags` (aka `dispatch_flags_t`) is a fixed sized enumeration.  The `rawValue` is going to be `UInt32` on Windows, which should conform to `BinaryInteger` ...

**Comment by ktopley-apple** [comment]
I agree, and it builds successfully in the Swift CI.

**Comment by compnerd** [comment]
Unfortunately, Swift CI doesn't build for Windows just yet.  I've been working on the Foundation bring up for Windows recently, so I am definitely starting to exercise the paths that were not being fully exercised previously.

**Comment by compnerd** [comment]
I think I get why this fails on Windows, #445 should fix that

**Pull request merged**
