### PR TITLE
Added build-android script which will build libdispatch for Android

### PR DESCRIPTION
**Pull request by amraboelela**
Also has fix for https://bugs.swift.org/browse/SR-5885

### CODE REVIEW

**Comment by amraboelela** [comment]
@milseman pls check this, thanks

**Comment by compnerd** [comment]
Are you aware of the cmake based build system?  You should be able to build for android using CMake by doing:

```
cmake -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_NDK=<path to android NDK> <path to source to libdispatch>
```

**Comment by amraboelela** [comment]
Hi @compnerd have you tried it? 

Thanks

**Comment by compnerd** [comment]
@amraboelela I've not built it myself, but have worked with a number of others to build it.  If there are issues with that, I'm happy to help resolve those.

**Comment by dgrove-oss** [comment]
echoing @compnerd comment; we're hopefully just about to switch to CMake as the build system for libdispatch.  So, android build should be based on that, not autotools.

**Comment by MadCoder** [comment]
Agreed, please do not use autoconf for new work.

Also, once we update the documentation (hint @compnerd) to explain how to hold CMake we should write the instructions here, I'd like to avoid having 10 different scripts for every single port. Instead the CMake build should do the right thing based on a single (or at most two) arguments.

**Comment by compnerd** [comment]
@MadCoder, yeah, thats the next change that I intend to make -- the docs!

**Comment by amraboelela** [comment]
I ran:
cmake -DCMAKE_SYSTEM_NAME=Android \
    -DCMAKE_SYSTEM_VERSION=21 \
    -DCMAKE_ANDROID_NDK=$ANDROID_NDK_PATH

I got:

-- Configuring done
-- Generating done
-- Build files have been written to: /home/amr/swift/swift-corelibs-libdispatch

~/swift/swift-corelibs-libdispatch$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	CMakeCache.txt
	CMakeFiles/
	CTestTestfile.cmake
	TryRunResults.cmake
	build-android-cmake
	cmake_install.cmake
	dispatch/CMakeFiles/
	dispatch/CTestTestfile.cmake
	dispatch/cmake_install.cmake
	man/CMakeFiles/
	man/CTestTestfile.cmake
	man/cmake_install.cmake
	os/CMakeFiles/
	os/CTestTestfile.cmake
	os/cmake_install.cmake
	private/CMakeFiles/
	private/CTestTestfile.cmake
	private/cmake_install.cmake
	src/CMakeFiles/
	src/CTestTestfile.cmake
	src/cmake_install.cmake
	tests/CMakeFiles/
	tests/CTestTestfile.cmake
	tests/cmake_install.cmake

I couldn't find libdispatch.so

**Comment by compnerd** [comment]
You need to run the make command to actually build it.  CMake generates the build rules.

**Comment by amraboelela** [comment]
Ah ok, what about make install? Can I make it copy the libdispatch.so to the android toolchain, like what I did in the original script?

**Comment by amraboelela** [comment]
So cmake is just a replacement of autoconf and configure?

**Comment by amraboelela** [comment]
Now I got:
-- Configuring done
-- Generating done
-- Build files have been written to: /home/amr/swift/swift-corelibs-libdispatch
[  1%] Building C object CMakeFiles/BlocksRuntime.dir/src/BlocksRuntime/data.c.o
cc: error: unrecognized command line option ‘-Wdocumentation’
cc: error: unrecognized command line option ‘-Wconstant-conversion’
cc: error: unrecognized command line option ‘-Wbool-conversion’
cc: error: unrecognized command line option ‘-Wenum-conversion’
cc: error: unrecognized command line option ‘-Wassign-enum’
cc: error: unrecognized command line option ‘-Wshorten-64-to-32’
cc: error: unrecognized command line option ‘-Wnewline-eof’
cc: error: unrecognized command line option ‘-Winfinite-recursion’
cc: error: unrecognized command line option ‘-Warray-bounds-pointer-arithmetic’
cc: error: unrecognized command line option ‘-Watomic-properties’
cc: error: unrecognized command line option ‘-Wcomma’
cc: error: unrecognized command line option ‘-Wconditional-uninitialized’
cc: error: unrecognized command line option ‘-Wcovered-switch-default’
cc: error: unrecognized command line option ‘-Wduplicate-enum’
cc: error: unrecognized command line option ‘-Wexpansion-to-defined’
cc: error: unrecognized command line option ‘-Widiomatic-parentheses’
cc: error: unrecognized command line option ‘-Wimplicit-fallthrough’
cc: error: unrecognized command line option ‘-Wnullable-to-nonnull-conversion’
cc: error: unrecognized command line option ‘-Wobjc-interface-ivars’
cc: error: unrecognized command line option ‘-Wover-aligned’
cc: error: unrecognized command line option ‘-Wstatic-in-inline’
cc: error: unrecognized command line option ‘-Wsuper-class-method-mismatch’
cc: error: unrecognized command line option ‘-Wtautological-compare’
cc: error: unrecognized command line option ‘-Wunguarded-availability’
CMakeFiles/BlocksRuntime.dir/build.make:62: recipe for target 'CMakeFiles/BlocksRuntime.dir/src/BlocksRuntime/data.c.o' failed
make[2]: *** [CMakeFiles/BlocksRuntime.dir/src/BlocksRuntime/data.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/BlocksRuntime.dir/all' failed
make[1]: *** [CMakeFiles/BlocksRuntime.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by compnerd** [comment]
Yeah, CMake is a replacement for autoconf/automake.  I think you failed to specify `-DCMAKE_C_COMPILER=/path/to/clang and -DCMAKE_CXX_COMPILER=/path/to/clang++` so you are using the system compiler, which is not what you want.  Yes, you can copy `libdispatch.so` as you used to, or you can use the install rule with the generator (e.g. `ninja install`).

**Comment by amraboelela** [comment]
Ok I am able to generate libdisptach.so file now inside the src directory. What about Dispatch.swiftmodule file, I need this one too. How can I generate it?

**Comment by compnerd** [comment]
You need to provide the path to the swift compiler `-DCMAKE_SWIFT_COMPILER=/path/to/swiftc`, that should generate `Dispatch.swiftmodule`.

**Comment by amraboelela** [comment]
So I am ending up giving back all the parameters i used to pass to configure before :)

What about making it release instead of debug?

Also I noticed that the generated lib dispatch.so file is 641KB while before it was 909KB, do u know why?

**Comment by amraboelela** [comment]
Now I am using:
cmake -DCMAKE_SYSTEM_NAME=Android \
    -DCMAKE_SYSTEM_VERSION=21 \
    -DCMAKE_ANDROID_NDK=$ANDROID_NDK_PATH \
    -DCMAKE_C_COMPILER=$SWIFT_ANDROID_BUILD_PATH/llvm-linux-x86_64/bin/clang \
    -DCMAKE_CXX_COMPILER=$SWIFT_ANDROID_BUILD_PATH/llvm-linux-x86_64/bin/clang++ \
    -DCMAKE_SWIFT_COMPILER=$SWIFT_ANDROID_BUILD_PATH/swift-linux-x86_64/bin/swiftc

make

And I got:
../src/libdispatch.so: undefined reference to `_T0s14CountableRangeVMa'
../src/libdispatch.so: undefined reference to `_T0Sus13BinaryIntegersWP'
../src/libdispatch.so: undefined reference to `_T0s9OptionSetPsE12intersectionxxF'
../src/libdispatch.so: undefined reference to `_T0s26DefaultRandomAccessIndicesVyxGs10Collectionss01_bC9IndexableRzlWa'
../src/libdispatch.so: undefined reference to `_T0SvN'
../src/libdispatch.so: undefined reference to `_T0s5Int64Vs13SignedIntegersWP'
../src/libdispatch.so: undefined reference to `_T0s9OptionSetPsE5unionxxF'
../src/libdispatch.so: undefined reference to `_T0SVN'
../src/libdispatch.so: undefined reference to `_T0S2SSgSPys4Int8VG14validatingUTF8_tcfC'
../src/libdispatch.so: undefined reference to `_T0SPMa'
../src/libdispatch.so: undefined reference to `swift_endAccess'
../src/libdispatch.so: undefined reference to `_T0s10CollectionPsE6prefix11SubSequenceQzSiF'
../src/libdispatch.so: undefined reference to `_T0s27_allocateUninitializedArraySayxG_BptBwlFSS_Tgq5'
../src/libdispatch.so: undefined reference to `_T0s17RandomAccessSliceVyxGs23BidirectionalCollectionss01_aB9IndexableRzlWa'
../src/libdispatch.so: undefined reference to `_T0s10SetAlgebraPssAARz7ElementQz012ArrayLiteralC0RtzlExSayAFG05arrayE0d_tcfC'
../src/libdispatch.so: undefined reference to `_T0s22RandomAccessCollectionMp'
../src/libdispatch.so: undefined reference to `_swift_release'
../src/libdispatch.so: undefined reference to `_T0s25ExpressibleByArrayLiteralMp'
../src/libdispatch.so: undefined reference to `_T0s19_emptyStringStorages6UInt32Vvp'
../src/libdispatch.so: undefined reference to `_T0s15UnsignedIntegerPss010FixedWidthB0RzsAARzlExqd__cs06BinaryB0Rd(long, float __restrict,  const)'
../src/libdispatch.so: undefined reference to `_T0SuMa'
../src/libdispatch.so: undefined reference to `_T0S2Sx26stringInterpolationSegment_tcs23CustomStringConvertibleRzlufC'
../src/libdispatch.so: undefined reference to `_T0s9OptionSetPssAARzs17FixedWidthInteger8RawValueRpzlE16formIntersectionyxF'
../src/libdispatch.so: undefined reference to `_T0SQMa'
../src/libdispatch.so: undefined reference to `_T0s10CollectionPsE3mapSayqd__Gqd__7ElementQzKcKlF'
../src/libdispatch.so: undefined reference to `_T0Sis11_StrideablesWP'
../src/libdispatch.so: undefined reference to `_T0s9OptionSetPssAARzs17FixedWidthInteger8RawValueRpzlExycfC'
../src/libdispatch.so: undefined reference to `_T0s23_BidirectionalIndexableMp'
../src/libdispatch.so: undefined reference to `_T0SR11baseAddressSPyxGSgvg'
../src/libdispatch.so: undefined reference to `_T0Sq7flatMapqd__SgABxKcKlF'
../src/libdispatch.so: undefined reference to `_T0s8SequencePsE18_preprocessingPassqd__Sgqd__yKcKlF'
../src/libdispatch.so: undefined reference to `_T0s5Int16Vs13BinaryIntegersWP'
../src/libdispatch.so: undefined reference to `_T0s23_BidirectionalIndexablePsE8distance13IndexDistanceQz0D0Qz4from_AG2totF'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
tests/CMakeFiles/dispatch_plusplus.dir/build.make:97: recipe for target 'tests/dispatch_plusplus' failed
make[2]: *** [tests/dispatch_plusplus] Error 1
CMakeFiles/Makefile2:361: recipe for target 'tests/CMakeFiles/dispatch_plusplus.dir/all' failed
make[1]: *** [tests/CMakeFiles/dispatch_plusplus.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by compnerd** [comment]
You know, its probably better off if you use `build-script`.  It already sets up all the parameters for you.  The errors sound like you're failing to link against the swift stdlib.

**Comment by amraboelela** [comment]
But using the old fashion configure was working fine. Don't think build-script will help build lib dispatch for android, I tried it. My original build-android was based on: https://github.com/SwiftJava/swifty-robot-environment/blob/master/util/prepare_environment/060_build_corelibs_libdispatch.sh

**Comment by amraboelela** [comment]
I am going to try build-script and let you know the results

**Comment by amraboelela** [comment]
Is there in cmake something equivalent to configure --with-swift-toolchain="$SWIFT_ANDROID_TOOLCHAIN_PATH/usr" ?

**Comment by amraboelela** [comment]
I tried this before:

${SWIFT_PATH}/swift/utils/build-script \
    -R \
    --android \
    --android-ndk ${ANDROID_NDK_PATH} \
    --android-api-level 21 \
    --android-icu-uc "${ANDROID_ICU_PATH}/armeabi-v7a" \
    --android-icu-uc-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/common" \
    --android-icu-i18n "${ANDROID_ICU_PATH}/armeabi-v7a" \
    --android-icu-i18n-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/i18n" \
    --foundation --install-foundation \
    --llbuild --install-llbuild \
    --lldb --install-lldb \
    --install-swift \
    --swiftpm --install-swiftpm \
    --xctest --install-xctest \
    --install-destdir=${SWIFT_ANDROID_TOOLCHAIN_PATH}

And it didn't build lib foundation.so for Android

But I'll try now build-script --libdispatch --install-libdispatch

**Comment by amraboelela** [comment]
Do I have to run cmake before running the build-script?

**Comment by amraboelela** [comment]
So I tried all of the that, using build-script and cmake, but it didn't work. It generated libdispatch.so for linux but not for Android.

**Comment by amraboelela** [comment]
Reverted my changes to go back to use autoconf as this is the currently only fully working solution.

**Comment by compnerd** [comment]
A few people involved with the swift android efforts have actually tried it with the CMake system before we merged it into the tree.  It actually does work but requires that you set up the parameters that are necessary.  You should figure out why you were failing to link against the swift runtime.

**Comment by awakecoding** [comment]
Something looks fishy, where is the Android toolchain file, and why is there no android target architecture specified? I successfully built it on Linux using the given instructions, but the resulting test executables run correctly on my Linux host, when they definitely shouldn't.

**Comment by compnerd** [comment]
@awakecoding The Android toolchain file has been merged into CMake itself properly.  https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android

**Comment by milseman** [comment]
CC @modocache and (long-shot) @ewmailing, both of whom I believe have experience with Android and using CMake.

**Comment by amraboelela** [comment]
I think someone need to put more technical explanations in one of the README.md files about how the ninja, build.ninja, CMakeLists.txt, cmake, build.py, autoconf, configure, ... works, because it can be really confusing :)

**Comment by compnerd** [comment]
@amraboelela `build.ninja` is more implementation details of ninja, which is the build system that you select.  You could just as well as use make.  I don't think it is reasonable to explain how the build tools function.  `cmake` is the meta-build system and is very well documented at cmake.org.  `autoconf`/`automake` (and `configure`) are part of autotools, which is intended to be removed.

I would really recommend that you look at how the build for swift works, because it will build libdispatch using cmake for SourceKit.  The same invocation with the additional parameters I mentioned above will enable building for android.

**Comment by awakecoding** [comment]
@compnerd I've been using cmake for years and did a whole bunch of stuff with it, and I still feel like something may be missing from the current cmake build system for Android. I managed to build it for a bunch of different architectures (x86, x86_64, arm, arm64), but not after making portability patches to both the build system AND the source code.

You can find the changes I've done here: https://github.com/apple/swift-corelibs-libdispatch/compare/master...wayk:wayk

For ARM, here is what my full cmake command looks like: `cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_SYSTEM_NAME=Android -DCMAKE_SYSTEM_VERSION=21 -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_NDK=/opt/android-sdk/ndk-bundle -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang ..`

1) the check for sem_init in the pthread library fails because the -lpthread linker flag breaks the compilation check. (reference: https://stackoverflow.com/questions/38666609/cant-find-lpthread-when-cross-compile-to-arm). I disabled the check and defined USE_POSIX_SEM for Android.

2) I added the TARGET_OS_EMBEDDED definition for compilation, otherwise it's going to use a lot of code not meant for an "embedded" target like Android. I found this on a ticket somewhere online, I can't find

3) I added an option to disable dtrace, because it would pick it up from the Linux host, causing compilation errors in the generated provider.h.

4) The macro "TRASHIT" was used in one place without being defined. This macro exists, but it's not defined in regular conditions, which is odd. I added it unconditionally (src/internal.h).

5) src/io.c made use of valloc(), which is not provided by Android's bionic libc. I added a static replacement function to make it work.

6) src/shims/hw_config.h was using pthread_getaffinity_np which is not detected and not present on Android. Adding an && !defined(__ANDROID__) to make use of the next possible code works.

7) src/shims/yield.h was using pthread_yield_np which is not detected, and not present on Android. I added a definition for Android that uses sched_yield from sched.h instead.

As for the rest, they are warnings I didn't bother fixing yet. Since the default is to enable all warnings and to consider warnings as errors, I just disabled temporarily -Werror. The code on my branch compiles with no warnings as long as it is a 64-bit architecture. The remaining warnings occur when building arm (quite important!) and x86. The 32-bit warnings are mostly the same as those I'm getting when building for 32-bit Linux.

I'm sorry for the long post, but I'm either doing something very wrong, or there are a bunch of things that still require fixing in order to get proper Android builds.

**Comment by amraboelela** [comment]
@awakecoding My changes are very similar to yours, I just made similar changes to the source files like what you did. I am going to publish it here.

**Comment by awakecoding** [comment]
@amraboelela how about we make a bunch of small pull requests for individual fixes, so they can get reviewed individually? Also, I see you've reverted to using the older build system rather than cmake. Maybe try again with my fixes and report back. To build each architecture, create subdirectories in the source tree and then generate with each of the following CMAKE_ANDROID_ARCH_ABI: armeabi-v7a, arm64-v8a, x86, x86_64.

**Comment by compnerd** [comment]
`TARGET_OS_EMBEDDED` makes sense ... if that was being passed in manually before.  But, I imagine that a few of the errors that you are seeing may be the result of that.  A couple of items look more like workarounds rather than proper fixes (e.g. the `TRASHIT` definition, dtrace handling, pthread_sem checks, etc).  The question is, what was different in the compiler invocation previously that has changed now with cmake.  Figuring out the differences in flags is the right approach to fixing those issues rather than just changing the behaviour.

**Comment by amraboelela** [comment]
I suggest creating another pull request which uses cmake. I am currently busy with build-android for libFoundation :)

**Comment by awakecoding** [comment]
@compnerd totally agree, I'm new to libdispatch, so I just made it work for now without expecting my changes to be merged as-is. I was hoping one of the experienced devs could help me figure out the proper way to address the issues encountered. For dtrace, I noticed the previous build system had an option "use_dtrace", so it makes sense to have one in cmake as well. As for the pthread sem_init check, it will likely have to be handled differently for Android, because of the way the check is done. You can find the log for the error inside CMakeFiles/CMakeError.log for the check, it fails because of the test executable uses -lpthread, which fails on Android.

**Comment by amraboelela** [comment]
@awakecoding I was actually able to create libdispatch.so for Android with cmake. My blocker was how to create Dispatch.swiftmodule. I am able to do that with configure but not with cmake.

**Comment by compnerd** [comment]
@amraboelela so, if you disable the tests, you should just be able to specify `CMAKE_SWIFT_COMPILER` as the path to `swiftc` and have that get generated.

**Comment by amraboelela** [comment]
@compnerd I just tried it, and then when I ran build-android for libFoundation I got:
/NSData.swift:19:8: error: module file was created for incompatible target x86_64-unknown-linux-gnu: /home/amr/swift/swift-corelibs-libdispatch/src/swift/Dispatch.swiftmodule
import Dispatch

**Comment by amraboelela** [comment]
I added build-android-cmake if someone wanna try it

**Comment by awakecoding** [comment]
@amraboelela I'm not using swift, as I'm only interested in libdispatch for pure C usage. As for your issue with Dispatch.swiftmodule, I'm pretty sure it can be done with CMake. Can you describe what's involved? Otherwise you can ask in the #cmake channel on freenode, the devs are really helpful.

**Comment by compnerd** [comment]
FYI, the last set of improvements for libdispatch's build should take care of the issues that you saw with `dispatch_plusplus`.  Note that you will need to add `-DENABLE_SWIFT=YES` to build the swift overlay.

**Comment by amraboelela** [comment]
Actually the latest “improvement” caused the swift/utils/android/build-toolchain to fail :), as it is no longer generate Dispatch.swiftmodule for linux, it used to do that before.

**Comment by compnerd** [comment]
As I mentioned, you will need to add the explicit flag to enable the swift part of the build :-).  We most definitely generate that as it is done as part of the build for the swift SDK overlay :-).

**Comment by amraboelela** [comment]
This is what the android/build-toolchain looks like:

${SWIFT_PATH}/swift/utils/build-script \
    -R \
    --android \
    --android-ndk ${ANDROID_NDK_PATH} \
    --android-api-level 21 \
    --android-icu-uc "${ANDROID_ICU_PATH}/armeabi-v7a" \
    --android-icu-uc-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/common" \
    --android-icu-i18n "${ANDROID_ICU_PATH}/armeabi-v7a" \
    --android-icu-i18n-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/i18n" \
    --llbuild --install-llbuild \
    --lldb --install-lldb \
    --install-swift \
    --libdispatch --install-libdispatch \
    --swiftpm --install-swiftpm \
    --install-destdir=${SWIFT_ANDROID_TOOLCHAIN_PATH}

Can I add -DENABLE_SWIFT=YES to build-script parameters?

**Comment by compnerd** [comment]
Yeah, you could add that to the build script parameters as extra parameters.  However, I think that is the core of the issue -- I never wired up the `--android-ndk` parameter into the CMake invocation for libdispatch.  That should be easy to do in build-script-impl though.

**Comment by amraboelela** [comment]
So will it look like this?

${SWIFT_PATH}/swift/utils/build-script
-R
--android
--android-ndk ${ANDROID_NDK_PATH}
--android-api-level 21
--android-icu-uc "${ANDROID_ICU_PATH}/armeabi-v7a"
--android-icu-uc-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/common"
--android-icu-i18n "${ANDROID_ICU_PATH}/armeabi-v7a"
--android-icu-i18n-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/i18n"
--llbuild --install-llbuild
--lldb --install-lldb
--install-swift
--libdispatch --install-libdispatch
--swiftpm --install-swiftpm
--install-destdir=${SWIFT_ANDROID_TOOLCHAIN_PATH}
-DENABLE_SWIFT=YES

Doesn't look right, as it is different from other parameters

**Comment by amraboelela** [comment]
Another weird thing I noticed, when I run:

${SWIFT_PATH}/swift/utils/build-script \
    -R \
    --llbuild --install-llbuild \
    --install-swift \
    --lldb --install-lldb \
    --libdispatch --install-libdispatch \
    --install-destdir=${SWIFT_ANDROID_TOOLCHAIN_PATH}

I get:
swift-android-toolchain$ find . -name "*ispatch*"
./home/amr/swift/build/Ninja-ReleaseAssert/swift-linux-x86_64/tools/SourceKit/libdispatch-prefix
./home/amr/swift/build/Ninja-ReleaseAssert/swift-linux-x86_64/tools/SourceKit/libdispatch-prefix/include/dispatch
./home/amr/swift/build/Ninja-ReleaseAssert/swift-linux-x86_64/tools/SourceKit/libdispatch-prefix/include/dispatch/dispatch.h
./home/amr/swift/build/Ninja-ReleaseAssert/swift-linux-x86_64/tools/SourceKit/libdispatch-prefix/lib/libdispatch.so
./home/amr/swift/build/Ninja-ReleaseAssert/swift-linux-x86_64/tools/SourceKit/libdispatch-prefix/lib/swift/linux/x86_64/Dispatch.swiftdoc
./home/amr/swift/build/Ninja-ReleaseAssert/swift-linux-x86_64/tools/SourceKit/libdispatch-prefix/lib/swift/linux/x86_64/Dispatch.swiftmodule

**Comment by ephemer** [comment]
I'm currently blocked by this issue, also because I need to build Foundation, which relies on Dispatch as well. Does anyone have a status update on this? @amraboelela?

@compnerd the invocation in https://github.com/apple/swift-corelibs-libdispatch/blob/master/INSTALL.md only seems to build x86_64 libraries on my machine (Ubuntu 16.04) and an invocation of swift's `build-script` like this:

    utils/build-script \
        -R \
        --android \
        --android-ndk $NDK \
        --android-api-level 21 \
        --android-icu-uc $LIBICONV_ANDROID/armeabi-v7a/ \
        --android-icu-uc-include $LIBICONV_ANDROID/armeabi-v7a/icu/source/common \
        --android-icu-i18n $LIBICONV_ANDROID/armeabi-v7a/ \
        --android-icu-i18n-include $LIBICONV_ANDROID/armeabi-v7a/icu/source/i18n \
        --libdispatch --install-libdispatch \
        --foundation --install-foundation \
        --llbuild --install-llbuild \
        --lldb --install-lldb \
        --swiftpm --install-swiftpm \
        --xctest --install-xctest \
        --install-swift \
        '--swift-install-components=autolink-driver;compiler;clang-builtin-headers;stdlib;swift-remote-mirror;sdk-overlay;dev' \
        --install-prefix=/usr --install-destdir=$SWIFT_INSTALLATION_PATH

... doesn't seem to build dispatch for Android, only for the host system (unless I'm just looking in the wrong place? It's definitely not in `build/Ninja-ReleaseAssert/lib/swift/android`)

I'd greatly appreciate any help or updates on this

**Comment by compnerd** [comment]
Yeah, the install doesn't place it under `android` but rather `linux`.  That is an easy fix.  I don't use the `build-script`, so can you please extract the cmake invocation?

**Comment by compnerd** [comment]
@ephemer sure the dry run output should contain the CMake invocation.  Did you pass CMAKE_SYSTEM_PROCESSOR?

**Comment by compnerd** [comment]
Okay, with apple/swift-corelibs-libdispatch#312 I was able to build a libdispatch.so for android.  I didn't have the swift stdlib available for android, so I didn't test the swift integration.

**Comment by amraboelela** [comment]
I tried build-android-cmake
and i got:
...
-- Configuring incomplete, errors occurred!
See also "/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeOutput.log".
See also "/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeError.log".

**Comment by amraboelela** [comment]
CMakeError.log contains:

Determining if the VQ_VERYLOWDISK exist failed with the following output:
Change Dir: /home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_aefd8/fast"
/usr/bin/make -f CMakeFiles/cmTC_aefd8.dir/build.make CMakeFiles/cmTC_aefd8.dir/build
make[1]: Entering directory '/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_aefd8.dir/CheckSymbolExists.c.o
/usr/bin/cc  -D_GNU_SOURCE   -o CMakeFiles/cmTC_aefd8.dir/CheckSymbolExists.c.o   -c /home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: ‘VQ_VERYLOWDISK’ undeclared (first use in this function)
   return ((int*)(&VQ_VERYLOWDISK))[argc];
                   ^
/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/cmTC_aefd8.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_aefd8.dir/CheckSymbolExists.c.o' failed
make[1]: *** [CMakeFiles/cmTC_aefd8.dir/CheckSymbolExists.c.o] Error 1
make[1]: Leaving directory '/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_aefd8/fast' failed
make: *** [cmTC_aefd8/fast] Error 2

**Comment by amraboelela** [comment]
Run Build Command:"/usr/bin/make" "cmTC_ec569/fast"
/usr/bin/make -f CMakeFiles/cmTC_ec569.dir/build.make CMakeFiles/cmTC_ec569.dir/build
make[1]: Entering directory '/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ec569.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_ec569.dir/CheckSymbolExists.c.o   -c /home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_ec569
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ec569.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_ec569.dir/CheckSymbolExists.c.o  -o cmTC_ec569
CMakeFiles/cmTC_ec569.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ec569.dir/build.make:97: recipe for target 'cmTC_ec569' failed
make[1]: *** [cmTC_ec569] Error 1
make[1]: Leaving directory '/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ec569/fast' failed
make: *** [cmTC_ec569/fast] Error 2

Determining if the function _pthread_workqueue_init exists failed with the following output:
Change Dir: /home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2e36f/fast"
/usr/bin/make -f CMakeFiles/cmTC_2e36f.dir/build.make CMakeFiles/cmTC_2e36f.dir/build
make[1]: Entering directory '/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2e36f.dir/CheckFunctionExists.c.o
/usr/bin/cc  -D_GNU_SOURCE  -DCHECK_FUNCTION_EXISTS=_pthread_workqueue_init   -o CMakeFiles/cmTC_2e36f.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_2e36f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2e36f.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=_pthread_workqueue_init    CMakeFiles/cmTC_2e36f.dir/CheckFunctionExists.c.o  -o cmTC_2e36f
CMakeFiles/cmTC_2e36f.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `_pthread_workqueue_init'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_2e36f.dir/build.make:97: recipe for target 'cmTC_2e36f' failed
make[1]: *** [cmTC_2e36f] Error 1

Determining if the function mach_absolute_time exists failed with the following output:
Change Dir: /home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6fc57/fast"
/usr/bin/make -f CMakeFiles/cmTC_6fc57.dir/build.make CMakeFiles/cmTC_6fc57.dir/build
make[1]: Entering directory '/home/amr/swift/swift-corelibs-libdispatch/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6fc57.dir/CheckFunctionExists.c.o
/usr/bin/cc  -D_GNU_SOURCE  -DCHECK_FUNCTION_EXISTS=mach_absolute_time   -o CMakeFiles/cmTC_6fc57.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_6fc57
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6fc57.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=mach_absolute_time    CMakeFiles/cmTC_6fc57.dir/CheckFunctionExists.c.o  -o cmTC_6fc57
CMakeFiles/cmTC_6fc57.dir/CheckFunctionExists.c.o: In function `main':
CheckFunctionExists.c:(.text+0x15): undefined reference to `mach_absolute_time'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_6fc57.dir/build.make:97: recipe for target 'cmTC_6fc57' failed
make[1]: *** [cmTC_6fc57] Error 1

**Comment by alblue** [comment]
This PR has gone stale. Please rebase and fix the conflicts before re-opening.

**Pull request closed without merging**
