### PR TITLE
Remove version number used in 'available' attribute for non-specific platform '*'.

### PR DESCRIPTION
**Pull request by dingobye**
This patch aims to make swift-corelibs-libdispatch adapted to [this PR](https://github.com/apple/swift/pull/18895), which warns for version number in 'available' attribute for non-specific platform '*'.

### CODE REVIEW

**Comment by jrose-apple** [comment]
Do we care about watchOS and tvOS too? tvOS version numbers match iOS's, but watchOS's don't.

**Comment by ktopley-apple** [comment]
I agree with Jordan - the tvOS and watchOS deprecations should also be included.

**Comment by jrose-apple** [comment]
I don't think I or Ding knows for sure what those should be! It's also a little funny that these are *just* in corelibs-dispatch, which is never used on iOS/tvOS/watchOS. Or did we miss some in the overlays too?

**Comment by dingobye** [comment]
Thank you for the feedbacks, Jordan and Kim!

Can we just remove those lines of `@available(*, deprecated: 8.0, ...)` here? Just take a look at [the relevant part in master](https://github.com/apple/swift/blob/master/stdlib/public/SDK/Dispatch/Queue.swift#L51). There are attributes for four platforms macOS/iOS/tvOS/watchOS, among which I think keeping only macOS is sufficient for _swift-corelibs-libdispatch_ project.

**Comment by jrose-apple** [comment]
I suspect that SCD is trying to match the contents of the Darwin overlay exactly for most of these files, and that they should therefore be kept in sync.

**Comment by dingobye** [comment]
Alright, let's keep it in sync. This is a conservative solution anyway.

**Comment by jrose-apple** [comment]
@swift-ci Please test Linux

**Pull request merged**
