### PR TITLE
build: add a dependency on the swift compiler

### PR DESCRIPTION
**Pull request by compnerd**
Add a dependency on the swift compiler to ensure that a change to the
compiler will rebuild the swift portions.

### CODE REVIEW

**Comment by compnerd** [comment]
CC @gottesmm @das @MadCoder

**Comment by jrose-apple** [comment]
This definitely makes sense to me.

**Comment by gottesmm** [comment]
This is just a cmake thing and should be safe to take. It is just adding a dependency on the swift compiler changing, so it shouldn't affect anyones build. Just for safety I will test.

**Comment by gottesmm** [comment]
@swift-ci test

**Pull request merged**
