### PR TITLE
Adopt Sendable in DispatchQueue and similar types

### PR DESCRIPTION
**Pull request by ktoso**
A few well known types like DispatchSemaphore, DispatchIO, DispatchGroup, DispatchQueue, DispatchSource should all be Sendable.

resolves rdar://123284763

### CODE REVIEW

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please test linux

**Review by MaxDesiatov — APPROVED** [review]

**Review by rokhinip — APPROVED** [review]

**Comment by ktoso** [comment]
Also `@Sendable` to .async APIs as they are on Apple platforms.
This solves rdar://123284763

Thanks for review!

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-ci please test

**Pull request merged**
