### PR TITLE
build: add dtrace USDT probe support

### PR DESCRIPTION
**Pull request by compnerd**
Add the missing support for dtrace header script support.

### CODE REVIEW

**Comment by compnerd** [comment]
@dgrove-oss does this work for you?  (I dont have dtrace installed, so if you could test this, it would be wonderful)

**Comment by dgrove-oss** [comment]
Almost, you need to add the directory in which provider.h is generated to the includes.  With the additional patch below it works for me.

diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index ca6ef75..bdc9162 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -115,6 +115,7 @@ endif()
 target_include_directories(dispatch
                            PRIVATE
                              ${CMAKE_BINARY_DIR}
+                             ${CMAKE_CURRENT_BINARY_DIR}
                              ${CMAKE_SOURCE_DIR}
                              ${CMAKE_CURRENT_SOURCE_DIR}
                              ${CMAKE_SOURCE_DIR}/private)

**Comment by compnerd** [comment]
@dgrove-oss updated

**Comment by das** [comment]
awesome, thanks!

**Pull request merged**
