### PR TITLE
Update deliveries value atomically to avoid potential race condition

### PR DESCRIPTION
**Pull request by seabaylea**
The libdispatch CI has an intermittent failure in `dispatch_read2` with the following reported in the log file:
```
[BEGIN] dispatch_read deliveries
	Actual: 319
	Expected: 320
[FAIL] dispatch_read deliveries (dispatch_read2.c:386)
	dispatch_read2.c:386
```
it looks like this could be cause by a race condition on `deliveries`, so switching to use atomic updates.

### CODE REVIEW

**Comment by MadCoder** [comment]
no, that can't be the bug, dispatch_read serializes everything through a single dispatch queue, so there is serialization already. FWIW we also have that issue on OS X and I have never taken the time to track it down yet.

**Comment by seabaylea** [comment]
Ok, so does that means that the blocks are executed in serial, not just the reads occurring in serial and enqueueing the blocks with the correct data, which can then be executed in parallel?

**Comment by MadCoder** [comment]
it's more about async I/O in general to avoid wasting thraeds while the data is being fetched by the kernel. but as you can see `dispatch_read(*fd, siz, q, b);` the queue argument mean that the results will be asynced to `q` so everything is serialized

what I think happens for real is that we do 240 writes, but one of the read coalesces two writes in a single read, and that the test assumptions about how the kernel works are wrong.

**Comment by seabaylea** [comment]
Ok - if that's the case, are you happy for me to disable the test so that we can get the CI running cleanly? 

Long term we could look at modifying the test to only check if the data size is correct if we think the number of deliveries might legitimately be smaller than expected.

**Comment by MadCoder** [comment]
sure, FWIW it's just a hunch that the test is wrong, I have never taken the time to double check.

**Comment by seabaylea** [comment]
Ok - created PR #135 to disable the test.

**Comment by MadCoder** [comment]
so for this test, the thing is, it expects that because it does a ` 		usleep(10000);` between writes, reads won't coalesce. this is actually not always the case.

the equality test should be made a test_less_or_equal instead, it's not the important test anyway.

**Comment by MadCoder** [comment]
closing as this hasn't made progress. as I said the right fix is to move to a `<=` assertion instead of `==`

**Pull request closed without merging**
