### PR TITLE
Replace uses of @_silgen_name with uses of a shims header.

### PR DESCRIPTION
**Pull request by jrose-apple**
Said shims header is in the main Swift repo because it's shared with the Darwin Dispatch overlay. This is the same effort as apple/swift#5854, but for corelibs.

No intended functionality change.

### CODE REVIEW

**Comment by jrose-apple** [comment]
apple/swift#6033

@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift#6033

@swift-ci Please test

**Comment by jrose-apple** [comment]
```
TestFoundation: src/common/knote.c:155: knote_disable: Assertion `!(kn->kev.flags & 0x0008)' failed.
```

@phausler, @dgrove-oss, have you seen this before?

**Comment by phausler** [comment]
nope, have not seen that particular failure before. Looks like a failure inside of the kqueue implementation

**Comment by dgrove-oss** [comment]
The knote assertion showed up in some of the CI tests of #162.  I believe @MadCoder decided it was not blocking and merged anyways.   I think it is extremely unlikely that this PR could be the cause of the kqueue assertion.

**Comment by jrose-apple** [comment]
The Dispatch tests did pass anyway.

**Comment by dgrove-oss** [comment]
@jrose-apple I assume we still want to get this PR merged.  Do you want me to pick it up and resolve the conflicts (plus another conflict I'm about to add with #198) or do you have time to resolve them yourself?

**Comment by jrose-apple** [comment]
You're welcome to pick them up if you want. They're not urgent, just general cleanup as we try to get away from the awfulness of matching up unrelated declarations.

**Comment by dgrove-oss** [comment]
The dispatch conflicts were easy to resolve, but we need to get https://github.com/apple/swift/pull/6033 merged before we can merge this one (otherwise it won't build).   Since it seems like a low priority thing, I'm dropping it for now.

**Comment by jrose-apple** [comment]
Picked this up again, because why not finish it off.

apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
Oops, this probably isn't correct because I forgot to remove SWIFT_CC from things.

**Comment by jrose-apple** [comment]
apple/swift#6033

@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift#6033

@swift-ci Please test

**Comment by jrose-apple** [comment]
Hm, swift-ci…

apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
…

apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
apple/swift#6033
@swift-ci Please test

**Comment by jrose-apple** [comment]
Okay, I'll try doing it the other way around.

**Comment by jrose-apple** [comment]
Passed here: https://github.com/apple/swift/pull/6033#issuecomment-364315147

**Pull request merged**
